tupla = []

frase = input("Escriu dues paraules: ")

tupla.append(frase)

print(tupla.count("q"))
print(tupla.count("w"))
print(tupla.count("e"))
print(tupla.count("r"))
print(tupla.count("t"))
print(tupla.count("y"))
print(tupla.count("u"))
print(tupla.count("i"))
print(tupla.count("o"))
print(tupla.count("p"))
print(tupla.count("a"))
print(tupla.count("s"))
print(tupla.count("d"))
print(tupla.count("f"))
print(tupla.count("g"))
print(tupla.count("h"))
print(tupla.count("j"))
print(tupla.count("k"))
print(tupla.count("l"))
print(tupla.count("ñ"))
print(tupla.count("z"))
print(tupla.count("x"))
print(tupla.count("c"))
print(tupla.count("v"))
print(tupla.count("b"))
print(tupla.count("n"))
print(tupla.count("m"))
print(frase)